name = "StableTasks"
uuid = "91464d47-22a1-43fe-8b7f-2d57ee82463f"
authors = ["Mason Protter <mason.protter@icloud.com>"]
version = "0.1.0"

[compat]
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]